version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-probabilidad
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HEALTH_ENABLED: "true"
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
      - ../frontend/themes:/opt/keycloak/themes
      - kc-data:/opt/keycloak/data
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'exec 3<>/dev/tcp/127.0.0.1/8080'"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - app-network


  quizdb:
    image: postgres:latest
    container_name: postgres-quiz
    restart: always
    environment:
      POSTGRES_USER: quiz
      POSTGRES_PASSWORD: quiz
      POSTGRES_DB: quizdb
    ports:
      - "5432:5432" # si no quieres exponer la BD, puedes borrar esta línea
    volumes:
      - quizdb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quiz -d quizdb"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - app-network

  quarkus-probabilidad:
    build: ../backend
    container_name: quarkus-probabilidad
    restart: unless-stopped
    environment:
      # OIDC / Keycloak (se sobreponen a application.properties)
      QUARKUS_OIDC_AUTH_SERVER_URL: ${QUARKUS_OIDC_AUTH_SERVER_URL}
      QUARKUS_OIDC_CLIENT_ID: ${QUARKUS_OIDC_CLIENT_ID}
      QUARKUS_OIDC_APP_TYPE: ${QUARKUS_OIDC_APP_TYPE}
      QUARKUS_OIDC_AUDIENCE: ${QUARKUS_OIDC_AUDIENCE}
      QUARKUS_OIDC_ROLES_SOURCE: ${QUARKUS_OIDC_ROLES_SOURCE}
      QUARKUS_OIDC_ROLE_PATH: ${QUARKUS_OIDC_ROLE_PATH}
      ADMIN_URL: ${ADMIN_URL}
      REALM: ${REALM}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}

      # CORS
      QUARKUS_HTTP_CORS: ${QUARKUS_HTTP_CORS}
      QUARKUS_HTTP_CORS_ORIGINS: ${QUARKUS_HTTP_CORS_ORIGINS}
      QUARKUS_HTTP_CORS_METHODS: ${QUARKUS_HTTP_CORS_METHODS}

      # DB dentro de docker: usar el nombre del servicio, no localhost
      DB_URL: jdbc:postgresql://quizdb:5432/quizdb
      DB_USER: quiz
      DB_PASS: quiz
    depends_on:
      keycloak:
        condition: service_healthy
      quizdb:
        condition: service_healthy
    ports:
      - "8081:8080"  # fuera del contenedor será http://localhost:8081
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend-probabilidad
    depends_on:
      quarkus-probabilidad:
        condition: service_started
    ports:
      - "5173:80"   # localhost:5173 -> nginx (puerto 80 dentro del contenedor)
    networks:
      - app-network

volumes:
  quizdb-data:
  kc-data:

networks:
  app-network:
    driver: bridge
